# Site settings
title: "Ryan Schneberger's Resume"
description: "Digital resume for Ryan Schneberger"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ryan Schneberger"
resume_title:                   "Datacenter Operations Engineer"
resume_contact_email:           "ryanschneberger@gmail.com"
resume_contact_telephone:       "609-549-1742"
resume_contact_address:         "426 Redwood Ave, Galloway NJ 08205"
resume_header_contact_info: "426 Redwood Ave, Galloway NJ 08205 | 609-549-1742 | ryanschneberger@gmail.com"
resume_header_intro: "<p>My career path has lead me to a wonderful company with intelligent coworkers who I continue to learn from and grow with each and every day. I am a detail oriented, personable, individual with an analytical mind that enjoys problem solving. I have over a decade of knowledge working in Windows and Linux environments. I have a strong understanding of cloud infrastructure components, software, agile development practices, project management, hardware, and best practices. I am ambitious and continuously looking for ways to improve processes within my department. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/rschneberger"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/ryan.schneberger"
  resume_linkedin_url:          "https://www.linkedin.com/in/rschneberger"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://rschneberger.github.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
